# See also: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

# This is the default and blank issues are useful so let's keep 'em.
blank_issues_enabled: true

contact_links:
  - name: Create Your Issues
    url: https://github.com/MoBagel/awesome-sso/issues
    about: User support, questions, bugfixes.
